# Generated by Django 4.1 on 2023-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsonsale",
            name="productdescription",
            field=models.CharField(max_length=800),
        ),
    ]
