# Generated by Django 4.1 on 2023-05-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0002_alter_productsonsale_productdescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsonsale", name="productPrice", field=models.FloatField(),
        ),
    ]
