# Generated by Django 4.1 on 2023-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0004_buyitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyitem", name="item_pk", field=models.IntegerField(),
        ),
    ]
