# Generated by Django 4.1 on 2023-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0005_alter_buyitem_item_pk"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("Last_name", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("address1", models.CharField(max_length=50)),
                ("address2", models.CharField(max_length=50, null=True)),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zip", models.CharField(max_length=50)),
                ("payment", models.CharField(max_length=50)),
                ("name_on_card", models.CharField(max_length=50)),
                ("credit_card_number", models.CharField(max_length=50)),
                ("expiration", models.CharField(max_length=50)),
                ("CVV", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
            ],
        ),
    ]
