# Generated by Django 4.1 on 2023-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0006_orderform"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderform",
            name="ordered_items_pk",
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
